exclude: '^docs/conf.py'

repos:
- repo: https://github.com/ambv/black
  rev: 22.3.0 # key required by pre-commit, but ignored in practice, because we use the "system" version of the tool, set in setup.cfg
  hooks:
  - id: black
    language: system

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
    exclude: ambr
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
    exclude:
      README.rst
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=no']

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.254  # key required by pre-commit, but ignored in practice, because we use the "system" version of the tool, set in setup.cfg
  hooks:
  - id: ruff
    language: system
